server:
  port: 8081
spring:
  datasource: 
    username: root
    password: Pa$$w0rd
    url: jdbc:mysql://localhost:3306/hyperprof?useSSL=false&serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      "[format_sql]": true