spring:
  flyway:
    enabled: true
  web:
    locale: pt_BR
  profiles:
    active: ${HYPERPROF_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
